// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/org/jdryad/com/messages/wired-message.proto

package org.jdryad.com.messages;

public final class WiredMessageProtos {
  private WiredMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class WiredMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use WiredMessage.newBuilder() to construct.
    private WiredMessage() {
      initFields();
    }
    private WiredMessage(boolean noInit) {}
    
    private static final WiredMessage defaultInstance;
    public static WiredMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public WiredMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jdryad.com.messages.WiredMessageProtos.internal_static_org_jdryad_com_messages_WiredMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jdryad.com.messages.WiredMessageProtos.internal_static_org_jdryad_com_messages_WiredMessage_fieldAccessorTable;
    }
    
    // required int32 messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private boolean hasMessageType;
    private int messageType_ = 0;
    public boolean hasMessageType() { return hasMessageType; }
    public int getMessageType() { return messageType_; }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessageType) return false;
      if (!hasPayload) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageType()) {
        output.writeInt32(1, getMessageType());
      }
      if (hasPayload()) {
        output.writeBytes(2, getPayload());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMessageType());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jdryad.com.messages.WiredMessageProtos.WiredMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jdryad.com.messages.WiredMessageProtos.WiredMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.jdryad.com.messages.WiredMessageProtos.WiredMessage result;
      
      // Construct using org.jdryad.com.messages.WiredMessageProtos.WiredMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.jdryad.com.messages.WiredMessageProtos.WiredMessage();
        return builder;
      }
      
      protected org.jdryad.com.messages.WiredMessageProtos.WiredMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.jdryad.com.messages.WiredMessageProtos.WiredMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jdryad.com.messages.WiredMessageProtos.WiredMessage.getDescriptor();
      }
      
      public org.jdryad.com.messages.WiredMessageProtos.WiredMessage getDefaultInstanceForType() {
        return org.jdryad.com.messages.WiredMessageProtos.WiredMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.jdryad.com.messages.WiredMessageProtos.WiredMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.jdryad.com.messages.WiredMessageProtos.WiredMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jdryad.com.messages.WiredMessageProtos.WiredMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.jdryad.com.messages.WiredMessageProtos.WiredMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jdryad.com.messages.WiredMessageProtos.WiredMessage) {
          return mergeFrom((org.jdryad.com.messages.WiredMessageProtos.WiredMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jdryad.com.messages.WiredMessageProtos.WiredMessage other) {
        if (other == org.jdryad.com.messages.WiredMessageProtos.WiredMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMessageType(input.readInt32());
              break;
            }
            case 18: {
              setPayload(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required int32 messageType = 1;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public int getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(int value) {
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = 0;
        return this;
      }
      
      // required bytes payload = 2;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jdryad.com.messages.WiredMessage)
    }
    
    static {
      defaultInstance = new WiredMessage(true);
      org.jdryad.com.messages.WiredMessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jdryad.com.messages.WiredMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jdryad_com_messages_WiredMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jdryad_com_messages_WiredMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/org/jdryad/com/messages/wired-mess" +
      "age.proto\022\027org.jdryad.com.messages\"4\n\014Wi" +
      "redMessage\022\023\n\013messageType\030\001 \002(\005\022\017\n\007paylo" +
      "ad\030\002 \002(\014B\024B\022WiredMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jdryad_com_messages_WiredMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jdryad_com_messages_WiredMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jdryad_com_messages_WiredMessage_descriptor,
              new java.lang.String[] { "MessageType", "Payload", },
              org.jdryad.com.messages.WiredMessageProtos.WiredMessage.class,
              org.jdryad.com.messages.WiredMessageProtos.WiredMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
